server:
  port: 8081
  servlet:
    context-path: /usermg
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermg?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
      additional-paths: scr/main/java
      additional-exclude: WEB-INF/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pengh.ssm.entity
logging:
  level:
    com.pengh.usermg.dao: debug
    com.pengh.usermg.redis: debug
swagger:
  base-package: com.pengh.usermg.controller