package com.pengh.usermg.dao;

import com.pengh.usermg.entity.GroupRoleRelation;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GroupRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long groupRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    int insert(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    int insertSelective(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    GroupRoleRelation selectByPrimaryKey(Long groupRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupRoleRelation record);
}