package com.pengh.usermg.dao;

import com.pengh.usermg.entity.Right;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated
     */
    int insert(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated
     */
    int insertSelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated
     */
    Right selectByPrimaryKey(Long trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Right record);
}