package com.pengh.usermg.dao;

import com.pengh.usermg.entity.RoleRightRelation;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RoleRightRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_right_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roleRightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_right_relation
     *
     * @mbg.generated
     */
    int insert(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_right_relation
     *
     * @mbg.generated
     */
    int insertSelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_right_relation
     *
     * @mbg.generated
     */
    RoleRightRelation selectByPrimaryKey(Long roleRightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_right_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_right_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleRightRelation record);
}