package com.pengh.usermg.dao;

import com.pengh.usermg.entity.UserRoleRelation;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    UserRoleRelation selectByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRoleRelation record);
}