package com.pengh.usermg.dao;

import com.pengh.usermg.entity.UserGroupRelation;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserGroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group_relation
     *
     * @mbg.generated
     */
    int insert(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group_relation
     *
     * @mbg.generated
     */
    int insertSelective(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group_relation
     *
     * @mbg.generated
     */
    UserGroupRelation selectByPrimaryKey(Long userGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGroupRelation record);
}