package com.pengh.usermg.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_group_role_relation
 */
public class GroupRoleRelation {
    /**
     * Database Column Remarks:
     *   记录标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_role_relation.group_role_id
     *
     * @mbg.generated
     */
    private Long groupRoleId;

    /**
     * Database Column Remarks:
     *   组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_role_relation.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     * Database Column Remarks:
     *   角色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_role_relation.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    public GroupRoleRelation(Long groupRoleId, Long groupId, Long roleId) {
        this.groupRoleId = groupRoleId;
        this.groupId = groupId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role_relation
     *
     * @mbg.generated
     */
    public GroupRoleRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_role_relation.group_role_id
     *
     * @return the value of t_group_role_relation.group_role_id
     *
     * @mbg.generated
     */
    public Long getGroupRoleId() {
        return groupRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_role_relation.group_role_id
     *
     * @param groupRoleId the value for t_group_role_relation.group_role_id
     *
     * @mbg.generated
     */
    public void setGroupRoleId(Long groupRoleId) {
        this.groupRoleId = groupRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_role_relation.group_id
     *
     * @return the value of t_group_role_relation.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_role_relation.group_id
     *
     * @param groupId the value for t_group_role_relation.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_role_relation.role_id
     *
     * @return the value of t_group_role_relation.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_role_relation.role_id
     *
     * @param roleId the value for t_group_role_relation.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}