package com.pengh.usermg.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_log
 */
public class Log {
    /**
     * Database Column Remarks:
     *   日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.log_id
     *
     * @mbg.generated
     */
    private Long logId;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.op_type
     *
     * @mbg.generated
     */
    private Integer opType;

    /**
     * Database Column Remarks:
     *   操作内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.gen_time
     *
     * @mbg.generated
     */
    private Date genTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated
     */
    public Log(Long logId, Integer opType, String content, Long userId, Date genTime) {
        this.logId = logId;
        this.opType = opType;
        this.content = content;
        this.userId = userId;
        this.genTime = genTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated
     */
    public Log() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.log_id
     *
     * @return the value of t_log.log_id
     *
     * @mbg.generated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.log_id
     *
     * @param logId the value for t_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.op_type
     *
     * @return the value of t_log.op_type
     *
     * @mbg.generated
     */
    public Integer getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.op_type
     *
     * @param opType the value for t_log.op_type
     *
     * @mbg.generated
     */
    public void setOpType(Integer opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.content
     *
     * @return the value of t_log.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.content
     *
     * @param content the value for t_log.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.user_id
     *
     * @return the value of t_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.user_id
     *
     * @param userId the value for t_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.gen_time
     *
     * @return the value of t_log.gen_time
     *
     * @mbg.generated
     */
    public Date getGenTime() {
        return genTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.gen_time
     *
     * @param genTime the value for t_log.gen_time
     *
     * @mbg.generated
     */
    public void setGenTime(Date genTime) {
        this.genTime = genTime;
    }
}