package com.pengh.usermg.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_org
 */
@Setter
@Getter
@AllArgsConstructor
public class Org {
    /**
     * Database Column Remarks:
     *   组织ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.org_id
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     * Database Column Remarks:
     *   父组织
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.p_org_id
     *
     * @mbg.generated
     */
    private Long pOrgId;

    private String pOrgName;

    /**
     * Database Column Remarks:
     *   组织名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.gen_time
     *
     * @mbg.generated
     */
    private Date genTime;

    /**
     * Database Column Remarks:
     *   组织描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.description
     *
     * @mbg.generated
     */
    private String description;


}