package com.pengh.usermg.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_role_relation
 */
public class UserRoleRelation {
    /**
     * Database Column Remarks:
     *   记录标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_relation.user_role_id
     *
     * @mbg.generated
     */
    private Long userRoleId;

    /**
     * Database Column Remarks:
     *   用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_relation.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   角色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_relation.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    public UserRoleRelation(Long userRoleId, Long userId, Long roleId) {
        this.userRoleId = userRoleId;
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role_relation
     *
     * @mbg.generated
     */
    public UserRoleRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_relation.user_role_id
     *
     * @return the value of t_user_role_relation.user_role_id
     *
     * @mbg.generated
     */
    public Long getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_relation.user_role_id
     *
     * @param userRoleId the value for t_user_role_relation.user_role_id
     *
     * @mbg.generated
     */
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_relation.user_id
     *
     * @return the value of t_user_role_relation.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_relation.user_id
     *
     * @param userId the value for t_user_role_relation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_relation.role_id
     *
     * @return the value of t_user_role_relation.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_relation.role_id
     *
     * @param roleId the value for t_user_role_relation.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}